# Generated by Django 3.1.4 on 2021-02-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='desription',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='is weak', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='metall',
            field=models.CharField(default='is strong', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='exist', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(max_length=32),
        ),
    ]
