# Generated by Django 3.2.4 on 2021-11-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210220_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='metall',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='just born', max_length=64),
        ),
    ]
