# Generated by Django 3.1.4 on 2021-02-19 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый модуль', max_length=64)),
                ('members', models.ManyToManyField(related_name='assigned_to_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
