# Generated by Django 3.1.5 on 2021-02-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Задание', max_length=64)),
                ('content', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='test1',
        ),
    ]
