# Generated by Django 3.1.5 on 2021-02-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
