# Generated by Django 3.2.4 on 2021-12-18 19:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.CharField(default='Новый модуль', max_length=64)),
                ('description', models.CharField(default='AAAA', max_length=1024)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 12, 18, 19, 8, 33, 208476, tzinfo=utc))),
                ('tasks_data', models.JSONField(default=list)),
                ('is_tasks_rnd', models.BooleanField(default=False)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
