# Generated by Django 3.1.4 on 2021-03-18 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя', max_length=64)),
                ('content', models.CharField(default='Условие', max_length=512)),
                ('answer', models.IntegerField(default=0)),
                ('options', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый модуль', max_length=64)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(blank=True, to='main.Group')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ManyToManyField(blank=True, to='main.UserNote')),
                ('tasks', models.ManyToManyField(blank=True, to='tasks.Task')),
            ],
        ),
    ]
