# Generated by Django 3.2.4 on 2021-11-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='module',
            name='marks',
        ),
    ]
