# Generated by Django 4.0.3 on 2022-03-14 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 19, 47, 28, 312711, tzinfo=utc)),
        ),
    ]
