# Generated by Django 3.2.4 on 2021-12-19 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 23, 58, 58, 500688, tzinfo=utc)),
        ),
    ]
