# Generated by Django 3.2.4 on 2021-12-17 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='tasks_rnd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 19, 57, 57, 780586, tzinfo=utc)),
        ),
    ]
