# Generated by Django 3.1.4 on 2021-03-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer_type',
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.RemoveField(
            model_name='task',
            name='options_answer',
        ),
        migrations.AddField(
            model_name='task',
            name='options_answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
