# Generated by Django 3.1.4 on 2021-02-19 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210219_2042'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='main.Group'),
        ),
        migrations.AlterField(
            model_name='module',
            name='marks',
            field=models.ManyToManyField(blank=True, to='tasks.Mark'),
        ),
        migrations.AlterField(
            model_name='module',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.Task'),
        ),
    ]
