# Generated by Django 4.0.3 on 2022-03-15 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_module_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 12, 31, 57, 85965, tzinfo=utc)),
        ),
    ]
