# Generated by Django 3.1.4 on 2021-03-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210311_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='correct_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='options_answer',
            new_name='options',
        ),
    ]
