# Generated by Django 3.2.4 on 2021-12-17 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211217_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='tasks_rnd',
            new_name='is_tasks_rnd',
        ),
        migrations.AlterField(
            model_name='module',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 20, 24, 53, 367454, tzinfo=utc)),
        ),
    ]
