# Generated by Django 3.2.4 on 2022-01-30 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_module_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 6, 32, 37, 650282, tzinfo=utc)),
        ),
    ]
