# Generated by Django 3.2.4 on 2022-01-30 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220130_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 7, 31, 14, 972080, tzinfo=utc)),
        ),
    ]
