# Generated by Django 3.1.4 on 2021-03-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210311_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
