# Generated by Django 3.1.5 on 2021-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='tasks',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
