# Generated by Django 3.1.4 on 2021-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usernote'),
        ('tasks', '0004_auto_20210312_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='marks',
            field=models.ManyToManyField(blank=True, to='main.UserNote'),
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
