# Generated by Django 3.2.4 on 2022-01-30 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_module_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 10, 1, 48, 391798, tzinfo=utc)),
        ),
    ]
