# Generated by Django 3.2.4 on 2021-12-12 21:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=1024)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 12, 12, 21, 45, 55, 659982, tzinfo=utc))),
                ('moduls_data', models.JSONField(default={})),
                ('id', models.CharField(default='AAAAAAAAAAAAAAAA', max_length=16, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
                ('moduls', models.ManyToManyField(blank=True, related_name='moduls', to='tasks.Module')),
            ],
        ),
    ]
