# Generated by Django 3.2.4 on 2021-12-19 23:58

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='mem',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem_adm',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mem_req',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='members_pending',
            field=models.ManyToManyField(blank=True, related_name='members_pending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 23, 58, 58, 501264, tzinfo=utc)),
        ),
    ]
