# Generated by Django 3.2.4 on 2021-12-17 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 19, 57, 57, 781328, tzinfo=utc)),
        ),
    ]
