# Generated by Django 3.2.4 on 2022-01-30 06:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20220130_0632'),
        ('groups', '0002_auto_20211219_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='moduls',
        ),
        migrations.AlterField(
            model_name='group',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 6, 32, 37, 652997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members_pending',
            field=models.ManyToManyField(blank=True, related_name='group_member_pending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='group',
            name='moduls_data',
        ),
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('user', models.ManyToManyField(related_name='user_mark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_data', models.DateTimeField(default=datetime.datetime(2022, 1, 30, 6, 32, 37, 651911, tzinfo=utc))),
                ('module', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_data', to='tasks.module')),
                ('user_marks', models.ManyToManyField(blank=True, related_name='module_data', to='groups.UserMark')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='moduls_data',
            field=models.ManyToManyField(blank=True, related_name='group_member', to='groups.ModuleData'),
        ),
    ]
