# Generated by Django 3.2.4 on 2022-01-30 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20220130_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledata',
            name='expiration_data',
        ),
        migrations.AddField(
            model_name='moduledata',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 7, 31, 14, 973700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 7, 31, 14, 974768, tzinfo=utc)),
        ),
    ]
