# Generated by Django 3.2.4 on 2022-01-30 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20220130_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 7, 31, 19, 892989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moduledata',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 7, 31, 19, 891705, tzinfo=utc)),
        ),
    ]
