# Generated by Django 3.2.4 on 2022-01-30 09:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_module_creation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_auto_20220130_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 9, 14, 14, 81892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members_pending',
            field=models.ManyToManyField(blank=True, related_name='member_pending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='moduls_data',
            field=models.ManyToManyField(blank=True, related_name='moduls_data', to='groups.ModuleData'),
        ),
        migrations.AlterField(
            model_name='moduledata',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 9, 14, 14, 80802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moduledata',
            name='module',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='module', to='tasks.module'),
        ),
        migrations.AlterField(
            model_name='moduledata',
            name='user_marks',
            field=models.ManyToManyField(blank=True, related_name='user_marks', to='groups.UserMark'),
        ),
        migrations.AlterField(
            model_name='usermark',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
