# Generated by Django 3.2.4 on 2022-01-30 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20220130_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermark',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 10, 1, 48, 392528, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='usermark',
            name='is_before_deadline',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 10, 1, 48, 394574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moduledata',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 10, 1, 48, 393498, tzinfo=utc)),
        ),
    ]
